### ISSUE TITLE
this is not working

### ISSUE THREAD

**Issue by El-Diablo1** [yonat/CheckmarkCollectionViewCell#1]
this is just an image placed on a cell , THAT's IT

**Comment by yonat** [comment]
Hi @El-Diablo1 , please provide minimal project that reproduces the problem. Thanks.

**Comment by El-Diablo1** [comment]
i'm sorry there was a problem at my end now it is working 👍 
but i have 1 more issue that checkbox image is showing on different places in different iphones 
kindly help

**Comment by yonat** [comment]
To help I need to see the code. Please link to a minimal project that reproduces the problem.
